### ISSUE TITLE
[BUG] S3 Delete 403 forbidden 이슈

### ISSUE THREAD

**Issue by semi-cloud** [ahachulTeam/ahachul_backend2#132]
## 문제 상황
- [x] S3 객체 저장은 되는데, 삭제 하려 하면 권한 에러가 발생(권한 설정 완료했는데도)

<img width="350" alt="image" src="https://github.com/ahachulTeam/ahachul_backend/assets/71436576/ea7a865f-06e5-4e0c-9b2f-228aa2800252">

## 문제 원인 및 해결과정
+ Iam 액세스 키 및 시크릿 키가 노출되면, AWS 에서 IAM 권한 정책에 자동으로 `AWSCompromisedKeyQuarantineV2` 를 추가
+ `AWSCompromisedKeyQuarantineV2` 에서는 보안을 위해 `DeleteObject` 권한을 Deny 하고 있어서 문제 발생
+ 액세스 토큰을 재발급 받아서 문제 해결

<img width="799" alt="image" src="https://github.com/ahachulTeam/ahachul_backend/assets/71436576/7ce168e2-64bc-4361-a8ee-174ebd0a6797">

```lml
 "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": [
                 ...
                "s3:DeleteBucket",    
                "s3:DeleteObject",    // 해당 권한이 막혀 있어서 문제 발생
                "s3:DeleteObjectVersion",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketAcl",
                "s3:PutBucketOwnershipControls",
                "s3:DeleteBucketPolicy",
                 ...
            ],
            "Resource": [
                "*"
            ]
        }
 ]
```

**Comment by semi-cloud** [comment]
@mangchhe 
으앙..드디어 원인 찾았습니다 확인해보셔요

**Comment by mangchhe** [comment]
@semi-cloud 
굳굳. `AWS 에서 IAM 권한 정책에 자동으로 AWSCompromisedKeyQuarantineV2 를 추가` 참고 하신 레퍼런스 공유좀 해주세요.

**Comment by semi-cloud** [comment]
https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AWSCompromisedKeyQuarantineV2.html
