### ISSUE TITLE
[BUG] 자바 힙 메모리 초과 에러

### ISSUE THREAD

**Issue by semi-cloud** [ahachulTeam/ahachul_backend2#186]
## 문제 상황
- [x] 힙 최대 크기가 250MB 나 되는 상황에서 `bulk insert` 시 힙 메모리 초과 예외 발생

## 서버 로그
![](https://velog.velcdn.com/images/semi-cloud/post/14717986-5e9f-461d-a778-073253090c1e/image.png)

## 문제 원인 및 해결과정
+ bulk insert 가 문제가 아니라, 170MB 정도의 대용량 파일을 한번에 가져와서 문제가 발생
+ BufferedReader로 나눠서 가져올 수도 있지만, objectMapper가 파싱하는 과정에서 여러 문제 발생
+ 따라서 파일 자체를 10개로 나누어서 가져오도록 변경

**Comment by mangchhe** [comment]
@semi-cloud 
다 하시면 MR 올려주세요.
