### ISSUE TITLE
[BUG] 유실물 리스트 및 상세 조회 시, commentCnt 매핑 오류

### ISSUE THREAD

**Issue by discphy** [ahachulTeam/ahachul_backend2#290]
## 문제 상황
- [x] commentCnt 필드가 매핑이 안되는 이슈

## 문제 원인 및 해결과정
+ 실제 매핑이 되어있지 않음

**Comment by createhb21** [comment]
실제 매핑이 되어있지 않음 ㅋㅋㅋㅋㅋ
