### ISSUE TITLE
[DISCUSS] AWS VPC 및 서브넷 설정 관련 논의

### ISSUE THREAD

**Issue by semi-cloud** [ahachulTeam/ahachul_backend2#4]
## 논의 사항
`EC2`와 `RDS` 모두 `private` 서브넷에 두고, `Bastion Host`를 사용하는 대신 `AWS SSM`을 통해 접근하려고 생각했습니다!
하지만 저희 서비스 기능을 보니까 혼잡도나 인증과 같은 외부 API 를 사용해야 해서 `NAT` 게이트웨이를 사용할 수 밖에 없더라구요(비용이 어마어마 합니다🥹)

[[AWS] VPC의 NAT 비용을 줄여보자](https://coding-groot.tistory.com/169) 글에 따르면 `NAT` 대신 리눅스 서버를 하나 더 두는 우회 방법이 있기는 하지만 여전히 추가 비용이 조금 발생하기는 합니다. 같이 의논해봐야 할 것 같아서 논의 올려요:)

### 정리
1.  EC2 public + RDS private : 비용 발생 X
2. EC2 public + RDS private : 비용 발생 O, 우회 방법 존재

**Comment by mangchhe** [comment]
@semi-cloud
EC2 public + RDS private 으로 구성하면 될 것 같습니다.
세미님이 적어주신 대로 우회하는 방법을 사용해도 비용이 추가로 나올 것으로 예상이 되는데 추후에 프로덕션 환경에 대해 팀원분들이랑 인프라 구성 비용 및 보안 관련해서 의논해보고 NAT을 이용할지 EC2를 하나 더 올려서 우회할 지 결정해도 될 것 같아요.

**Comment by semi-cloud** [comment]
@mangchhe 네 그러면 이번주 일요일 미팅 전까지 작업 완료해놓겠습니다!
