### ISSUE TITLE
[BUG] 테스트용 RDS로 설정 시 빌드 되지 않는 에러

### ISSUE THREAD

**Issue by semi-cloud** [ahachulTeam/ahachul_backend2#46]
## 문제 상황
- [x] 테스트 실행 시 임시 H2가 아닌 RDS와 연결하면 테스트 실패

## 서버 로그
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/71436576/231328656-42f8c63f-8d57-4271-8752-46326729e094.png">

## 문제 원인 및 해결과정
+ `Github-hosted runner` 에서 `private subnet` 에 존재하는 rds에 접속하지 못함
[Connecting to a private network](https://docs.github.com/en/actions/using-github-hosted-runners/connecting-to-a-private-network)

**Comment by semi-cloud** [comment]
@mangchhe
openId + load balancer 방식은 https까지 필요할 것 같아서, 일단 임시로 아래 방법 사용할까요? 
아니면 좀 걸리더라도 로드 밸런서 방식이 나을까요 아래 방식이 단점이 너무 많은 것 같아서 고민되네요

<img src="https://user-images.githubusercontent.com/71436576/231331052-a441b189-f9ee-4b66-bb9d-d82db0fd7211.png" width=50% height=50%>

**Comment by mangchhe** [comment]
@semi-cloud 
조금 더 배경에 대해서 디테일하게 설명해주실래요?
현재 이 이슈를 해결하기 위해서 openId + load balancer 이 왜 필요한 건지 궁금하네요.
참고하신 문서도 있으시면 링크도 같이 남겨주세요.

**Comment by semi-cloud** [comment]
@mangchhe 
[Connecting to a private network](https://docs.github.com/en/actions/using-github-hosted-runners/connecting-to-a-private-network) 보시면 1번 방법이 로드 밸런서 인증을 이용한 방식입니다.
일단 제가 이해한 대로는 대략 다음과 같은데 굳이 문서에 나와있는 방법 말고도 다른 방법이 있나 고민해봐야할 것 같네요👀

> 프라이빗 서브넷 접속 허용 과정
1. 깃허브에서 ID 토큰을 발급받는다.(OIDC)
2. 아하철 VPC에 존재하는 로드 밸런서에 OIDC 권한 설정을 해놓는다.
3. 요청 시 인증이 완료되면(깃허브 액션에서 발행한 토큰인지 및 허용 조직 및 레포/브랜치..etc가 일치하는 경우) 프라이빗 내부망에 접속이 가능해진다. 
<img width="828" alt="image" src="https://user-images.githubusercontent.com/71436576/231635534-c5b26cbe-5494-475e-91e7-cd2e05e18974.png">

하지만 [AWS 로드 밸런서 공식 문서](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html) 보시면 OIDC 방식은 Https에 대해서만 가능하다 나와있습니다!
<img width="869" alt="image" src="https://user-images.githubusercontent.com/71436576/231634557-80d416cb-2d03-4670-878f-4cdd3a760964.png">

내가 어떤 aws 서비스를 사용하기 위해 인증하는게 아니라 내부 망에 접속을 해야 하는 거라 로드 밸런서가 필요해보입니당..

**Comment by semi-cloud** [comment]
@mangchhe 
아무래도 로드 밸런서 생성 후 따로 설정이 필요해 보여서 공식 문서 찾아봤는데 OIDC 관련해서는 위에 보내드린 링크밖에 없고, [actions-oidc-gateway-example](https://github.com/github/actions-oidc-gateway-example) 보면 단순 명령어 예시 밖에 안나와있네요😫

[Configuring OpenID Connect in Amazon Web Services](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) 보면 IAM 만들어서 인증하는 것 같은데 S3같은 서비스도 아니여서 로드 밸런서에는 어떻게 적용을 해줘야 할 지 더 찾아봐야할 것 같아요 

혹시 이건가,,?[Accessing RDS in Private Isolated VPC using IAM Authentication]( https://repost.aws/questions/QU6_suvuqPTeuNYtgabDU9BQ/accessing-rds-in-private-isolated-vpc-using-iam-authentication)

**Comment by semi-cloud** [comment]
h2 로 테스트 하기로 했으니 일단 해당 이슈 닫겠습니다:)
