### ISSUE TITLE
[DISCUSS] 커뮤니티 ERD 초안

### ISSUE THREAD

**Issue by mangchhe** [ahachulTeam/ahachul_backend2#47]
## 논의 사항

- ERD 설계

## ERD 이미지

- erdcloud 링크 → [바로가기](https://www.erdcloud.com/d/6dKc9AeJrWc2ZQRNv)

![ahachul-erd](https://user-images.githubusercontent.com/50051656/231239856-1809a1c4-58c1-4a0e-98d1-cc75b3026479.png)

## ERD 구성 요소

- 테두리 안에 있는 내용들 테이블 추가
- 노랑색 : 커뮤니티 관련 테이블
  - 카테고리 : 자유, 정보, 유머 등 구분자
  - 게시글 : 게시글
  - 게시글 조회수 : 중복 조회 방지 테이블
  - 게시글 파일 : 게시글에 속한 파일
  - 좋아요 : 좋아요
  - 코멘트 : 댓글
- 주황색 : 공통 테이블
  - 파일 : 파일 관련 내용
  - 지역 : 서울, 부산 등 지역 구분
  - 지하철 노선 : 지역별 노선 종류

## 내용

- 우선 필수적으로 들어가야 하는 값들 생각해서 초안 작성해봤고 유실물 게시글 관련 내용들도 비슷하게 가져가면 될 것 같아요.
- 지역이랑 지하철 노선은 관련해서 기획 보충이 필요할 것 같아서 오늘 저녁에 @효범님이랑 허들할 예정인데 시간 되시면 세미님도 참여해주세요.
- 급하게 적어서 누락된 부분이 있을 수 있으니 이상한 점이나 의문점, 추가할 내용들 보이시면 코멘트 달아주세요.

## 참고사항

- ERD 상으로는 foreign key 연결해놨는데 논리적으로만 있고 물리적으로는 연결 안 할 생각입니다.

**Comment by semi-cloud** [comment]
헉 수고하셨어요 궁금한 점이 있어서 여쭤봅니다!

1. 파일 테이블을 따로 분리하고 중간에 매핑 테이블을 둠으로써 생기는 이점이 있을까요?
s3에서 가져온 url을 그냥 게시글 필드에 저장하는 형태로 했었는데 이렇게 하지 않으신 이유도 궁금해요!

2. 커뮤니티 게시글 조회수는 한 사람이 여러번 조회해도 하나로 카운팅 되기 위한 테이블이라고 이해했는데 맞을까요?
@createhb21 노션 기획 명세서에는 중복 조회 방지 관련 내용 없는 것 같아서 여쭤봅니당

**Comment by mangchhe** [comment]
@semi-cloud 
1. 이점이라기보단 게시글 하나에 파일을 여러 개 가질 수 있는 형태라서 게시글(1) : 파일(N)이라 다음과 같이 설계했습니다.
2. 네. 기획이 완벽하진 않아서 저희도 보고 부족하거나 필요한 부분에 대해서 챙겨서 같이 진행해야 할 것 같네요. 댓글 중복 방지도 마찬가지로 넣어두긴 했는데 오늘 효범님이랑 얘기 나눠보려구요.

**Comment by semi-cloud** [comment]
@mangchhe 
아하 파일이 여러개 업로드였군요 확인했습니다~

**Comment by createhb21** [comment]
좋네요 😆 
하기 노션 참고하시면서 설계해주시면 될 것 같아요 ! 
https://ahhachul.notion.site/3fd8aa54e8704a1fa057ca8b10db0fd7
추가적으로 게시글 신고하기 기능도 존재하는 것이 어떨까요 ? 
@mangchhe

**Comment by mangchhe** [comment]
@createhb21 
신고하기 기능은 사유 필요 없이 신고 버튼 누르면 신고가 되는 형태일까요?
그리고 신고하기하고 나서 해당 게시글에 대한 후속 조치에 대해서 알려주세요.
예를 들어 특정 게시글에 신고하기가 10회 이상 됐을 경우에 임시적으로 게시글 노출을 제한한다 등

**Comment by createhb21** [comment]
신고하기 기능은 커뮤니티 페이지, 유실물 페이지에 존재합니다. 
백엔드는 이 둘을 구분할 필요는 없으며 유저가 특정 기간동안(추가적 논의 필요합니다) 몇 번의 신고를 받았는지 카운트만 하면 됩니다. 
유저가 3번의 신고를 받을 경우,
-> "3번의 신고를 받았어요, 아하철에서 검토 후 댓글 작성 제한과 같은 별도의 조치가 취해질 수 있습니다." 
유저가 5번의 신고를 받을 경우
-> "5번의 신고를 받았어요, 아하철에서 검토 후 앱 사용 제한과 같은 별도의 조치가 취해질 수 있습니다."
메시지를 보내주며, 디비에서는 신고 카운트가 3일때와 5일때와 같은 특정 시점에 
불량 유저(?) 디비에 새롭게 그 유저와 유저의 신고 내용(히스토리)을 추가합니다.
그 디비에 들어간 시점부터 아하철 내 CS팀이 신고 사유를 검토 후 
실제 조취를 취할 지 말지 결정합니다.
실제 조취를 취하기로 한다면, 그 유저가 앱에 다시 돌아왔을 때 안내 메시지를 띄우며 댓글 작성 제한 혹은 앱 사용을 제한합니다.

1. 유저가 쓴 게시물이 불량 게시물이라서 다른 유저에게 신고 먹은 경우 
  - 3회 
    - 게시글 작성 제한 (3일)
    - 댓글 작성 제한 (3일)
  - 5회
    - 앱 사용 제한 (3일)
2. (추후 구현 예상) 앱 내 쪽지 서비스를 이용하다 신고 먹은 경우
3. (추후 구현 예상) 유저가 쓴 댓글이 불량 댓글이라서 다른 유저에게 신고 먹은 경우 

@mangchhe @semi-cloud

**Comment by createhb21** [comment]
추가적으로 게시물 신고 먹을 시 게시물도 블라인드 처리해야해요 ! 
ex) 신고 5회 이상일 시 게시물 블라인드 처리
@mangchhe @semi-cloud
