### ISSUE TITLE
[DISCUSS] 조회수와 좋아요 기능에서의 유저 중복 방지 방법 논의

### ISSUE THREAD

**Issue by semi-cloud** [ahachulTeam/ahachul_backend2#49]
## 논의 사항
현재 확인용 DB 테이블을 따로 만들어서 유저 중복을 방지하는데, 혹시 레디스에 저장하는 것은 어떤가요!?
불필요한 DB I/O 를 줄일 수도 있고 가벼운 데이터라고 생각해서요.
혹은 쿠키도 조작 위험만 빼면 탈취 당해도 게시글 정보만 들어가지 유저 관련 정보가 들어가는게 아니니까 괜찮을 것 같습니다..!

그리고 찾아보니까 다른 방법들도 있더라구요..! 그냥 공유해봅니당 (이미 찾아보셨을것 같지만😊)
1. IP 주소 / MAC address 로 판별
애초에 우리 서비스는 비회원 유저가 조회 불가능하므로 필요 없음
2. 쿠키 / 세션 사용 
쿠키는 조작 위험, 세션은 확장성이 낮다는 단점 존재

**Comment by semi-cloud** [comment]
### 쿠키 이용한 방법
1. 쿠키가 존재하지 않는다면 새로운 쿠키 생성 및 게시글 조회수 증가
2. 이후 요청 시 쿠키가 이미 존재한다면 조회수 증가는 패스

**Comment by mangchhe** [comment]
@semi-cloud 넵. 좋은 방법이네요.
하지만 인메모리 디비라서 디스크에 비해 메모리 크기가 크지 않아서 중복 조회수를 막기 위해서 조회수에 관련된 다량의 데이터를 넣는 게 괜찮을지는 검토해 볼 필요가 있을 것 같아요.
그리고 저희 중복 조회수를 허용한다고 기획을 주셔서 필요 없을 것 같아요.

**Comment by semi-cloud** [comment]
@mangchhe
아하 메모리 고려를 못했네요..! 바뀐 기획 건은 확인했습니당
그러면 ERD 커뮤니티 쪽도 수정해놓을게요

**Comment by mangchhe** [comment]
@semi-cloud 넵.
해당 이슈 해소된 것 같아 CLOSE 하겠습니다.
