### ISSUE TITLE
[DISCUSS] 유실물 페이지 ERD 초안

### ISSUE THREAD

**Issue by semi-cloud** [ahachulTeam/ahachul_backend2#50]
## 논의 사항

<img width="695" alt="image" src="https://user-images.githubusercontent.com/71436576/232260399-27ca5d28-3f1c-45cf-a057-abc3d487ee86.png">

### 내용
전체적인 구조는 커뮤니티와 비슷해서 유실물 테이블 관련해서 말씀드릴게요!

> 유실물 테이블
+ `lost_status` : 유실물을 찾은 상태 / 찾지 못한 상태 구분
+ `lost_origin` :  Lost112 / 앱 내부 출처 구분(필터링에 활용)
+ `null` 허용 데이터 : 사용자가 직접 올리는게 아닌 Lost112 에만 존재하는 정보들

### 코멘트
1. @mangchhe @createhb21 유실물 카테고리 필드를 일단 저장해두기로 한 이유가, 나중에 필터링에 추가될 수도 있다는 이유였는데 따로 카테고리 테이블을 만드려니까 종류가 너무 많아서 얘기 나눠봐야할 것 같아요! 그래서 일단 관련 내용 제외했습니다
<img src="https://user-images.githubusercontent.com/71436576/232228649-6ceb8c83-7012-459e-919f-c82ebc41d1ba.png" width=40% height=40%>

혹은 정보가 아래와 같이 표시되니까 세부 카테고리 말고 `>` 기준으로 구분해서 앞에 상위 카테고리만 사용해도 되구요
<img width="274" alt="image" src="https://user-images.githubusercontent.com/71436576/232229502-a416dd17-1604-4a15-b271-9e20d6dad9ba.png">

2. @mangchhe 댓글 테이블에 `order` 대신 부모인지 자식인지 구분하는 `status` 필드만으로도 되더라구요 order를 쓰면 정렬 하지 않아도 된다는 장점이 있는건가요!?
3. @mangchhe 파일 - 게시글 다대다 매핑 테이블에도 작성자/수정자/작성일자/수정일자가 들어가야 하나요??
4. @createhb21 혹시 기획 명세에 채팅(쪽지)라 되어 있는데 각각 구현이 좀 달라질 것 같아서 실시간 채팅인지 에타와 같은 쪽지 방식인지 결정 부탁드립니당
5. @createhb21 현재 기본 틀이 제목 + 내용 형식이여서 lost112에서 가져온 보관 장소나 보관 전화번호 등의 데이터를 어디에 보여줄지 정하는 UI가 추가로 필요할 것 같네요(분실물 찾기 탭)

**Comment by mangchhe** [comment]
1. 카테고리가 너무 무거운 느낌인데 간소화할 필요가 있을 것 같네요.
2. 댓글 상태(comment_status)는 어떤 용도일까요?
3. 공통 컬럼들은 기본적으로 다 들어가야 나중에 히스토리 트래킹할 수 있을 것 같네요.

**Comment by createhb21** [comment]
@semi-cloud 
1. 혹시 기획 명세에 채팅(쪽지)라 되어 있는데 각각 구현이 좀 달라질 것 같아서 실시간 채팅인지 에타와 같은 쪽지 방식인지 결정 부탁드립니당 
  - 에타의 쪽지 방식입니다 !
2. 현재 기본 틀이 제목 + 내용 형식이여서 lost112에서 가져온 보관 장소나 보관 전화번호 등의 데이터를 어디에 보여줄지 정하는 UI가 추가로 필요할 것 같네요(분실물 찾기 탭)
  - 넵 좋습니다 ! 
  
3. 카테고리가 너무 무거운 느낌인데 간소화할 필요가 있을 것 같네요.
  - 우선 2차 카테고리까지는 생각 안하고, 1차 카테고리만 생각하는 게 어떨까요 ? 뎁스를 1로만 우선 가는 거로요 !

**Comment by createhb21** [comment]
1. 가방
2. 악세사리
3. 책
4. 서류
5. 스포츠 
6. 악기
7. 의류
8. 전자기기 
9. 지갑 / 신분증 / 카드 
10. 기타 


이렇게만 해도 충분할 것 같은데 추가해야할 부분 있을까요 ?? 
@mangchhe @semi-cloud

**Comment by semi-cloud** [comment]
@mangchhe ERD 수정 완료했습니다
@createhb21 넵 확인했습니다!

**Comment by mangchhe** [comment]
@semi-cloud 

저희 테이블 네이밍을 일부 맞췄으면 해요.

일부 테이블명 post 빠져있음.

**유실물 테이블**
lost_name → title
대부분 컬럼에 접두사로 lost를 붙였는데 이미 주체가 유실물로 명확한 상황에서 앞에 접두사로 붙이는 건 불필요한 것 같아요.

**유실물 코멘트**
parent_lost_comment_id → upper_lost_comment_id

네이밍 이상하다고 생각하시는 거 있으시면 말씀해주세요.

**Comment by semi-cloud** [comment]
@mangchhe 
네이밍 반영 했습니다! ERD 확인 부탁드려요

**Comment by mangchhe** [comment]
@semi-cloud 
유실물 코멘트에 순서가 추가됐는데 잘못 넣으신걸까요?

@createhb21
저희 유실물 게시판에 조회수가 필요할까요?
그리고 커뮤니티 게시판도 조회수가 필요할까 싶네요. 실시간 HOT 게시물 알려줄 때 필요할까 싶었는데 좋아요 기능이 있는데 조회수가 크게 의미가 있나 싶어요.
필수로 필요한 기능인지 한 번 검토부탁드릴게요.

**Comment by semi-cloud** [comment]
@mangchhe 
아 반영이 안되었네요 삭제했습니다~!

주현님 테이블 네이밍은 유실인데 습득물 데이터까지 같은 테이블에 저장하기 위해 타입을 구분하려 하니까 아래와 같이 네이밍이 이상해지더라구요. 차라리 테이블을 분리하는게 나을까 싶기도 한데 그러기에는 중복되는 칼럼이 많아서 고민되네요. 어떻게 생각하시나요!?

<img width="193" alt="image" src="https://user-images.githubusercontent.com/71436576/232318969-18c7e968-9a79-496b-9889-203794960121.png">

**Comment by createhb21** [comment]
@mangchhe 조회수는 두 페이지 모두 살리고 싶네요 !
